---
title: "Figure1"
author: "Lyu"
date: "2024-06-05"
output: html_document
---

```{r}
library(Seurat)
library(tidyverse)
library(scales)
library(DropletUtils)
```

```{r correlation 10Xv3.1 and NOTE-seq}
# Load the dataset
reg.data <- Read10X(data.dir = "./10X/filtered_feature_bc_matrix/")
reg <- CreateSeuratObject(counts = reg.data, project = "10Xv3.1", min.cells = 3, min.features = 200)
reg.data <- NULL

D4sU.data <-  Read10X(data.dir = "./NOTEseq/filtered_feature_bc_matrix/")
D4sU <- CreateSeuratObject(counts = D4sU.data, project = "NOTEseq", min.cells = 3, min.features = 200)
D4sU.data <- NULL

# Merge datasets into one single seurat object and erase adj.matrix from memory to save RAM
alldata <- merge(reg,D4sU, add.cell.ids = c("10Xv3.1","NOTEseq"))
reg <- NULL
D4sU <- NULL

# Check the percentage of mitochondria and ribosome_Supplementary Fig1
alldata <- PercentageFeatureSet(alldata, "^MT-", col.name = "percent_mito")
alldata <- PercentageFeatureSet(alldata, "^RP[SL]", col.name = "percent_ribo")
feats <- c("percent_mito","percent_ribo")
VlnPlot(alldata, group.by = "orig.ident", features = feats, pt.size = 0, ncol = 2) 

# Normalize the data 
sc <- NormalizeData(alldata)

# Retrieve normalized matrices and compute the avergae 
## retrieve datasets
reg_gene_counts <- sc@assays$RNA@data[,1:2774]
D4sU_gene_counts <- sc@assays$RNA@data[,2775:5820]
## filter genes 
reg_gene_counts <- reg_gene_counts[rowSums(reg_gene_counts > 0) > 27, ]
D4sU_gene_counts <- D4sU_gene_counts[rowSums(D4sU_gene_counts > 0) > 30, ]
## select the genes captured in both pipeline
reg_gene <- as.data.frame(rownames(reg_gene_counts))
colnames(reg_gene) <- 'ID'
D4sU_gene <- as.data.frame(rownames(D4sU_gene_counts))
colnames(D4sU_gene) <- 'ID'
gene_in_both <- inner_join(reg_gene,D4sU_gene, by='ID')
## compute expression average
select_reg_gene_counts <- reg_gene_counts[rownames(reg_gene_counts) %in% gene_in_both$ID, ]
mean_reg_gene_counts <-as.data.frame(rowSums(select_reg_gene_counts)/2774) 
colnames(mean_reg_gene_counts) <- '10Xv3.1'
mean_reg_gene_counts$ID <- rownames(mean_reg_gene_counts)

select_D4sU_gene_counts <- D4sU_gene_counts[rownames(D4sU_gene_counts) %in% gene_in_both$ID, ]
mean_D4sU_gene_counts <-as.data.frame(rowSums(select_D4sU_gene_counts)/3046) 
colnames(mean_D4sU_gene_counts) <- 'NOTeseq'
mean_D4sU_gene_counts$ID <- rownames(mean_D4sU_gene_counts)

merg_fresh_fixed_mean <- inner_join(mean_reg_gene_counts,mean_D4sU_gene_counts, by='ID')
colnames(merg_fresh_fixed_mean)

# Plotting
RN <- nrow(merg_fresh_fixed_mean)
RS <- sample (RN, size=2000, replace =F)
RNAS <- merg_fresh_fixed_mean[RS,]

p <- RNAS%>% ggplot(aes(x=t10Xreg, y= t10X4sU))+
  geom_point(size=0.1,alpha=.3)+
  #remove background
  theme_classic() +
  theme(
    axis.text.y = element_text(size=6),
    axis.text.x = element_text(size = 6),
    axis.title = element_text(colour='black', size=7),
    legend.title=element_blank(),
    legend.key=element_blank(),
    axis.line.x = element_line(colour = "black", size=0.25),
    axis.line.y = element_line(colour = "black", size=0.25),
    axis.ticks.x = element_line(colour = "black", size = 0.25),
    axis.ticks.y = element_line(colour = "black", size = 0.25),
    )+
  scale_x_log10() +
  scale_y_log10() +
  annotation_logticks(sides = "bl", size=0.15, short = unit(0.05, "cm"), mid = unit(0.1, "cm"), long = unit(0.15, "cm")) +
  annotate(geom="text",x=0.01, y=1, label="PCC=0.93",size=2)+
  #xlim(0, 10)+
  #ylim(0, 10)+
  #change x and y labels
  xlab("10Xreg norm.UMI (log10)")+  
  ylab("10X4sU norm.UMI (log10)")
cor(log10(merg_fresh_fixed_mean$t10Xreg),log10(merg_fresh_fixed_mean$t10X4sU),method = 'pearson')
ggsave(filename = "reg_and_4sU_correlation.pdf",plot = p,width=45,height = 45,units = "mm", dpi = 300)

```

```{r T to C conversion ratio of new RNA}
# load dataset and subset ATCG info.

stat.info <- read.delim('./4sU_both_strand_all.tsv_q27_gene_anno_stat.txt',header = F)
stat.info <- stat.info %>% pivot_wider( names_from = 'V1', values_from = 'V2')

##
stat.info_T <- stat.info[1:5]
stat.info_T$T_to_A <- 100*(stat.info_T$T_to_A)/(stat.info_T$total_T)
stat.info_T$T_to_G <- 100*(stat.info_T$T_to_G)/(stat.info_T$total_T)
stat.info_T$T_to_C <- 100*(stat.info_T$T_to_C)/(stat.info_T$total_T)
stat.info_T$T_to_T <- NULL
stat.info_T$total_T <- NULL

stat.info_T <- stat.info_T %>% pivot_longer(cols=1:3 , names_to = 'name', values_to = 'value')
stat.info_T$type <- rep('T',3)

##
stat.info_A <- stat.info[6:10]
stat.info_A$A_to_A <- NULL
stat.info_A$A_to_G <- 100*(stat.info_A$A_to_G)/(stat.info_A$total_A)
stat.info_A$A_to_C <- 100*(stat.info_A$A_to_C)/(stat.info_A$total_A)
stat.info_A$A_to_T <- 100*(stat.info_A$A_to_T)/(stat.info_A$total_A)
stat.info_A$total_A <- NULL

stat.info_A <- stat.info_A %>% pivot_longer(cols=1:3 , names_to = 'name', values_to = 'value')
stat.info_A$type <- rep('A',3)

##
stat.info_G <- stat.info[11:15]
stat.info_G$G_to_A <- 100*(stat.info_G$G_to_A)/(stat.info_G$total_G)
stat.info_G$G_to_G <- NULL
stat.info_G$G_to_C <- 100*(stat.info_G$G_to_C)/(stat.info_G$total_G)
stat.info_G$G_to_T <- 100*(stat.info_G$G_to_T)/(stat.info_G$total_G)
stat.info_G$total_G <- NULL

stat.info_G <- stat.info_G %>% pivot_longer(cols=1:3 , names_to = 'name', values_to = 'value')
stat.info_G$type <- rep('G',3)

##
stat.info_C <- stat.info[16:20]
stat.info_C$C_to_A <- 100*(stat.info_C$C_to_A)/(stat.info_C$total_C)
stat.info_C$C_to_G <- 100*(stat.info_C$C_to_G)/(stat.info_C$total_C)
stat.info_C$C_to_C <- NULL
stat.info_C$C_to_T <- 100*(stat.info_C$C_to_T)/(stat.info_C$total_C)
stat.info_C$total_C <- NULL

stat.info_C <- stat.info_C %>% pivot_longer(cols=1:3 , names_to = 'name', values_to = 'value')
stat.info_C$type <- rep('C',3)

# merge
all.rate <- rbind(stat.info_T,stat.info_A,stat.info_G,stat.info_C)
all.rate$color <- c('black','black','red','black','black','black','black','black','black','black','black','black')

# ---------------
theme_man <- 
  theme_classic() +
  theme(
    axis.text.y = element_text(size=6),
    axis.text.x = element_text(size = 6),
    axis.title = element_text(colour='black', size=7),
    legend.title=element_blank(),
    legend.key=element_blank(),
    axis.line.x = element_line(colour = "black", size=0.25),
    axis.line.y = element_line(colour = "black", size=0.25),
    axis.ticks.x = element_line(colour = "black", size = 0.25),
    axis.ticks.y = element_line(colour = "black", size = 0.25)
    )

p <- ggplot(data = all.rate, mapping = aes(x = name , y = value, fill= color)) + 
         geom_bar(stat = "identity") +
  scale_fill_manual(values=c("#999999", 'red'))+theme_man + 
  theme(legend.position="none")+
  xlab(" ")+
  ylab("Mutation rate (%)")+
  geom_hline(yintercept = 0.1, linetype = "dashed",linewidth=0.25)+
  geom_hline(yintercept = 1.0, linetype = "dashed",,linewidth=0.25) +
  scale_y_continuous(breaks = c(0.1, 1.0, 1.4), labels = c("0.1", "1.0", '1.4'))+
  theme(axis.text.x = element_text(angle = 45, hjust = 0.8, vjust = 1))

ggsave(filename = "nucleiotide conversion rate.pdf",plot = p,width=45*1.5,height = 45,units = "mm", dpi = 300)

# plot T to C mutation rate in intronic reads/exonic reads ----------

intron_stat.info <- read.delim('./intron_both_strand_all.tsv_q27_gene_anno_stat.txt',header = F,row.names = 1)

intron_T_to_C <- intron_stat.info[which(rownames(intron_stat.info) == 'T_to_C'), ]
intron_total_T <- intron_stat.info[ which(rownames(intron_stat.info) == 'total_T'), ]
intron_T2C <- intron_T_to_C*100/intron_total_T

exon_stat.info <- read.delim('./exon_both_strand_all.tsv_q27_gene_anno_stat.txt',header = F,row.names = 1)

intron_T_to_C <- intron_stat.info[which(rownames(intron_stat.info) == 'T_to_C'), ]
intron_total_T <- intron_stat.info[ which(rownames(intron_stat.info) == 'total_T'), ]
intron_T2C <- intron_T_to_C*100/intron_total_T


exon_stat.info <- read.delim('./exon_both_strand_all.tsv_q27_gene_anno_stat.txt',header = F,row.names = 1)

exon_T_to_C <- exon_stat.info[which(rownames(exon_stat.info) == 'T_to_C'), ]
exon_total_T <- exon_stat.info[ which(rownames(exon_stat.info) == 'total_T'), ]
exon_T2C <- exon_T_to_C*100/exon_total_T

T2C_EI <-as.data.frame(rbind(intron_T2C=intron_T2C,exon_T2C=exon_T2C)) 
T2C_EI$name <- rownames(T2C_EI)

p <- ggplot(data = T2C_EI, mapping = aes(x = name , y = V1, fill= name)) + 
  geom_bar(stat = "identity") +
  scale_fill_manual(values=c("#999999", 'red'))+theme_man + 
  theme(legend.position="none")+
  xlab(" ")+
  ylab("Conversion rate (%)")+
  geom_hline(yintercept = 0.6, linetype = "dashed",linewidth=0.25)+
  geom_hline(yintercept = 6.0, linetype = "dashed",,linewidth=0.25) +
  scale_y_continuous(breaks = c(0.6, 6.0), labels = c("0.6", "6.0"))+
  theme(axis.text.x = element_text(angle = 45, hjust = 0.8, vjust = 1))

ggsave(filename = "EI_nucleiotide conversion rate.pdf",plot = p,width=45/2,height = 45,units = "mm", dpi = 300)

```

```{r examplary genes for new RNA ratio}
new_rna <- readRDS('eHAP_new_rna.rds')
old_rna <- readRDS('eHAP_old_rna.rds')

total_rna <- new_rna+old_rna
new_rna_ratio <- new_rna/total_rna

GAPDH_new <- new_rna[rownames(new_rna)== 'GAPDH', ]
 
MYC_new <- new_rna[rownames(new_rna)== 'MYC', ]

GAPDH <-as.data.frame(t(as.data.frame(new_rna_ratio[which(rownames(new_rna_ratio)=='GAPDH'),which(GAPDH_new>0)]))) 
colnames(GAPDH) <- 'value' 
GAPDH$type <- rep('GAPDH',nrow(GAPDH))
MYC <-as.data.frame(t(as.data.frame(new_rna_ratio[which(rownames(new_rna_ratio)=='MYC'),which(MYC_new>0)])))   
colnames(MYC) <- 'value' 
MYC$type <- rep('MYC',nrow(MYC))

GA_MYC <- rbind(GAPDH,MYC)

p <- GA_MYC %>%  ggplot( aes(x=type, y=value, fill=type)) +    
  geom_violin() +    
  theme_classic() +
  theme(
    axis.text.y = element_text(size=6),
    axis.text.x = element_text(size = 6),
    axis.title = element_text(colour='black', size=7),
    legend.title=element_blank(),
    legend.key=element_blank(),
    legend.position='none',
    axis.line.x = element_line(colour = "black", size=0.25),
    axis.line.y = element_line(colour = "black", size=0.25),
    axis.ticks.x = element_line(colour = "black", size = 0.25),
    axis.ticks.y = element_line(colour = "black", size = 0.25)
  )+   
  xlab("")+
  ylab('nascent UMI/total UMI ')
ggsave(filename = "examples_turnover rate.pdf",plot = p,width=45,height = 45,units = "mm", dpi = 300)

```


```{r comparison of gene and UMI detection}
# extract information regarding reads, gene counts and UMI counts
## 10xv3.1
mol.info.file <- '10xv3.1_molecule_info.h5'
reg_molinfo <- read10xMolInfo(mol.info.file)
reg_reads <- as.data.frame(reg_molinfo$data)
colnames(reg_reads)

reg_reads[1:10,]
reg_molinfo <- NULL
reg_reads_UMI <- reg_reads %>% group_by(cell) %>% summarise(Reads = sum(reads),UMI =n())
reg_cell_gene <- reg_reads[,c('cell','gene')] 
reg_cell_gene <- reg_cell_gene %>% distinct()
reg_cell_gene <- reg_cell_gene %>% group_by(cell) %>% summarise(Gene =n())

reg_reads_UMI_gene <- inner_join(reg_reads_UMI,reg_cell_gene,by='cell')

reg_reads_UMI_gene <- reg_reads_UMI_gene %>% arrange(desc(Reads))
reg_reads_UMI_gene_fil <- reg_reads_UMI_gene[1:10000,]
reg_reads_UMI_gene_fil$type <- rep('10xv3.1',10000)

## NOTEseq
mol.info.file <- 'NOTEseq_molecule_info.h5'
sU_molinfo <- read10xMolInfo(mol.info.file)
sU_reads <- as.data.frame(sU_molinfo$data)
colnames(sU_reads)

sU_reads[1:10,]
sU_molinfo <- NULL
sU_reads_UMI <- sU_reads %>% group_by(cell) %>% summarise(Reads = sum(reads),UMI =n())
sU_cell_gene <- sU_reads[,c('cell','gene')] 
sU_cell_gene <- sU_cell_gene %>% distinct()
sU_cell_gene <- sU_cell_gene %>% group_by(cell) %>% summarise(Gene =n())

sU_reads_UMI_gene <- inner_join(sU_reads_UMI,sU_cell_gene,by='cell')

sU_reads_UMI_gene <- sU_reads_UMI_gene %>% arrange(desc(Reads))
sU_reads_UMI_gene_fil <- sU_reads_UMI_gene[1:10000,]
sU_reads_UMI_gene_fil$type <- rep('NOTEseq',10000)

## merge datasets
reg_sU_comp <- rbind(reg_reads_UMI_gene_fil,sU_reads_UMI_gene_fil)
reg_sU_comp <- as.data.frame(reg_sU_comp)
## filter datasets
reg_sU_compfil <- reg_sU_comp %>% filter(Reads <= 100000)

# compare UMI------
sampleID <- c('NOTEseq','10xv3.1')

predict.nUMI <- sapply(sampleID,function(u){
  model1 <- lm(data = reg_sU_compfil %>% filter(type == u),formula = UMI ~ Reads)
  tmp <- predict(model1,data.frame(Reads=50000))
  return(round(as.numeric(tmp),0))
})

df.extra2 <- data.frame(Reads=rep(50000,2),UMI=predict.nUMI)
df.extra2$type <- rownames(df.extra2)

p <- ggplot(reg_sU_compfil,aes(Reads,UMI,col=type)) + geom_point(size=.2,shape=19,alpha=.3) + 
  geom_smooth(method="loess",se=F,size=.25,linetype=2,aes(group=type),col="black") +
  geom_vline(xintercept = 50000,col="grey30",linetype="dashed",linewidth=0.25) + 
  theme_classic() +
  theme(
    axis.text.y = element_text(size=6),
    axis.text.x = element_text(size = 6),
    axis.title = element_text(colour='black', size=7),
    legend.title=element_blank(),
    legend.key=element_blank(),
    legend.position = c(0.2, 0.8),
    legend.key.size = unit(0.1,"cm"),
    legend.key.width = unit(0.1,"cm"),
    legend.text = element_text(size=6),
    axis.line.x = element_line(colour = "black", size=0.25),
    axis.line.y = element_line(colour = "black", size=0.25),
    axis.ticks.x = element_line(colour = "black", size = 0.25),
    axis.ticks.y = element_line(colour = "black", size = 0.25)
   )+
  geom_point(data = df.extra2) +
  geom_text(data=df.extra2,aes(label=UMI),col="black",hjust=-.1,size=7/.pt) +
  xlim(0, 100000)+
  ylim(0, 75000)+
  #change x and y labels
  xlab("Reads")+  
  ylab("numbers of UMI")
ggsave(filename = "nUMI.pdf",plot = p,width=45*1.5,height = 45*1.5,units = "mm", dpi = 300)

# compare gene

predict.nGene <- sapply(sampleID,function(u){
  model1 <- loess(data = reg_sU_compfil %>% filter(type == u),formula = Gene ~ Reads)
  tmp <- predict(model1,data.frame(Reads=50000))
  return(round(as.numeric(tmp),0))
})


df.extra <- data.frame(Reads=rep(50000,2),Gene=predict.nGene)
df.extra$type <- rownames(df.extra)

p <-reg_sU_compfil %>% ggplot(aes(Reads,Gene,col=type)) + geom_point(size=.2,shape=19,alpha=.3) + 
  geom_smooth(method="loess",se=F,size=.25,linetype=2,aes(group=type),col="black") +
  geom_vline(xintercept = 50000,col="grey30",linetype="dashed",linewidth=.25) + 
  theme_classic() +
  theme(
    axis.text.y = element_text(size=6),
    axis.text.x = element_text(size = 6),
    axis.title = element_text(colour='black', size=7),
    legend.title=element_blank(),
    legend.key=element_blank(),
    legend.position = c(0.2, 0.8),
    legend.key.size = unit(0.1,"cm"),
    legend.key.width = unit(0.1,"cm"),
    legend.text = element_text(size=6),
    axis.line.x = element_line(colour = "black", size=0.25),
    axis.line.y = element_line(colour = "black", size=0.25),
    axis.ticks.x = element_line(colour = "black", size = 0.25),
    axis.ticks.y = element_line(colour = "black", size = 0.25)
    )+
  geom_point(data = df.extra) +
  geom_text(data=df.extra,aes(label=Gene),col="black",hjust=-.1,size=7/.pt) +
  #xlim(0, 100000)+
  #ylim(0, 75000)+
  xlab("Reads")+  
  ylab("numbers of gene")

ggsave(filename = "nGene.pdf",plot = p,width=45*1.5,height = 45*1.5,units = "mm", dpi = 300)

```

```{r barnyard experiment }
gem_classification <- read.csv("gem_classification.csv")
table(gem_classification$call)

GRCh38      mm10 Multiplet 
256       300        30 

p <- gem_classification%>% ggplot(aes(x=GRCh38, y= mm10, color=call))+
  geom_point(size=0.1,alpha=0.2)+
  #remove background
  theme_classic() +
  theme(
    axis.text.y = element_text(size=6),
    axis.text.x = element_text(size = 6),
    axis.title = element_text(colour='black', size=6),
    legend.title=element_blank(),
    legend.key=element_blank(),
    legend.text = element_text(size=6),
    legend.position = c(0.4, 0.8),
    axis.line.x = element_line(colour = "black", size=0.25),
    axis.line.y = element_line(colour = "black", size=0.25),
    axis.ticks.x = element_line(colour = "black", size = 0.25),
    axis.ticks.y = element_line(colour = "black", size = 0.25),
    )+
  guides(color = guide_legend(override.aes = list(size = 0.3)))+
  scale_color_hue(labels = c("Human(256)", "Mouse(300)",'Multiplet(30)'))+
  xlab("human(UMI#)")+  
  ylab("mouse(UMI#)")

ggsave(filename = "mix_assay.pdf",plot = p,width=45,height = 45,units = "mm", dpi = 300)
```

```{r subset dataset of NOTEseq for nascent RNA counting }
# QC and barcode extraction
D4sU.data <-  Read10X(data.dir = "./filtered_feature_bc_matrix/")
D4sU <- CreateSeuratObject(counts = D4sU.data, project = "NOTEseq", min.cells = 3, min.features = 200)
D4sU.data <- NULL
D4sU <- PercentageFeatureSet(D4sU, "^MT-", col.name = "percent_mito")

# subset cells
D4sU.filter <- subset(D4sU, nCount_RNA > 10000 & nCount_RNA < 50000 & percent_mito < 5)
# take cellular barcode
barcode_subset <- colnames(D4sU.filter)
write.table(barcode_subset,file = '4sU_barcode_st_subset.txt',sep = '\t',row.names = F,col.names = F,quote = F)
barcode_subset <- paste0('CB:Z:',barcode_subset)
write.table(barcode_subset,file = '4sU_barcode_subset.txt',sep = '\t',row.names = F,col.names = F,quote = F)

```

