---
title: "SupplementaryFigure5"
author: "Lyu"
date: "2024-06-20"
output: html_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(DESeq2)
library(EnhancedVolcano)
```

```{r SF 5c}
# datasets were deposited at GEO
# ------------
control_rep1 <-read.csv("T_contrl_1_S1_R1_001.fastq_slamdunk_mapped_filtered_tcount.tsv",sep = '\t', comment.char = "#")
control_rep2 <-read.csv("T_contrl_2_S2_R1_001.fastq_slamdunk_mapped_filtered_tcount.tsv",sep = '\t', comment.char = "#")

l250_rep1 <-read.csv("T_label_250_1_S3_R1_001.fastq_slamdunk_mapped_filtered_tcount.tsv",sep = '\t', comment.char = "#")
l250_rep2 <-read.csv("T_label_250_2_S4_R1_001.fastq_slamdunk_mapped_filtered_tcount.tsv",sep = '\t', comment.char = "#")

l500_rep1 <-read.csv("T_label_500_1_S5_R1_001.fastq_slamdunk_mapped_filtered_tcount.tsv",sep = '\t', comment.char = "#")
l500_rep2 <-read.csv("T_label_500_2_S6_R1_001.fastq_slamdunk_mapped_filtered_tcount.tsv",sep = '\t', comment.char = "#")

l1mM_rep1 <-read.csv("T_label_1K_1_S7_R1_001.fastq_slamdunk_mapped_filtered_tcount.tsv",sep = '\t', comment.char = "#")
l1mM_rep2 <-read.csv("T_label_1K_2_S8_R1_001.fastq_slamdunk_mapped_filtered_tcount.tsv",sep = '\t', comment.char = "#")


# subset -------------
control_rep1_ <- control_rep1[ , c(4,12)]
control_rep2_ <- control_rep2[ , c(4,12)]

l250_rep1_ <- l250_rep1[ , c(4,12)]
l250_rep2_ <- l250_rep2[ , c(4,12)]

l500_rep1_ <- l500_rep1[ , c(4,12)]
l500_rep2_ <- l500_rep2[ , c(4,12)]

l1mM_rep1_ <- l1mM_rep1[ , c(4,12)]
l1mM_rep2_ <- l1mM_rep2[ , c(4,12)]

# split transcriptsUTR ID -----------
transcript_ids_utr <- control_rep1_[,1]
tmp <- str_split_fixed(transcript_ids_utr, "_", 2)
control_rep1_ <- cbind(tmp,control_rep1_)
colnames(control_rep1_) <- c('transID','utr','Name', 'readCount')
con1 <- control_rep1_ %>% group_by(transID) %>% summarise(readCount = sum(readCount))
#con1 <- con1[con1$transID %in% geneIDC$ensembl_transcript_id_version, ]
#geneIDfil <- geneIDC[geneIDC$ensembl_transcript_id_version %in% con1$transID, ]
#colnames(geneIDfil) <- c('transID','ensembl_gene_id','external_transcript_name','external_gene_name')
#con1 <- inner_join(con1,geneIDfil, by="transID")
#con1 <- con1 %>% group_by(ensembl_gene_id) %>% summarise(readCount = sum(readCount))

transcript_ids_utr <- control_rep2_[,1]
tmp <- str_split_fixed(transcript_ids_utr, "_", 2)
control_rep2_ <- cbind(tmp,control_rep2_)
colnames(control_rep2_) <- c('transID','utr','Name', 'readCount')
con2 <- control_rep2_ %>% group_by(transID) %>% summarise(readCount = sum(readCount))

transcript_ids_utr <- l250_rep1_[,1]
tmp <- str_split_fixed(transcript_ids_utr, "_", 2)
l250_rep1_ <- cbind(tmp,l250_rep1_)
colnames(l250_rep1_) <- c('transID','utr','Name', 'readCount')
l2501 <- l250_rep1_ %>% group_by(transID) %>% summarise(readCount = sum(readCount))

transcript_ids_utr <- l250_rep2_[,1]
tmp <- str_split_fixed(transcript_ids_utr, "_", 2)
l250_rep2_ <- cbind(tmp,l250_rep2_)
colnames(l250_rep2_) <- c('transID','utr','Name', 'readCount')
l2502 <- l250_rep2_ %>% group_by(transID) %>% summarise(readCount = sum(readCount))

transcript_ids_utr <- l500_rep1_[,1]
tmp <- str_split_fixed(transcript_ids_utr, "_", 2)
l500_rep1_ <- cbind(tmp,l500_rep1_)
colnames(l500_rep1_) <- c('transID','utr','Name', 'readCount')
l5001 <- l500_rep1_ %>% group_by(transID) %>% summarise(readCount = sum(readCount))

transcript_ids_utr <- l500_rep2_[,1]
tmp <- str_split_fixed(transcript_ids_utr, "_", 2)
l500_rep2_ <- cbind(tmp,l500_rep2_)
colnames(l500_rep2_) <- c('transID','utr','Name', 'readCount')
l5002 <- l500_rep2_ %>% group_by(transID) %>% summarise(readCount = sum(readCount))

transcript_ids_utr <- l1mM_rep1_[,1]
tmp <- str_split_fixed(transcript_ids_utr, "_", 2)
l1mM_rep1_ <- cbind(tmp,l1mM_rep1_)
colnames(l1mM_rep1_) <- c('transID','utr','Name', 'readCount')
l1mM1 <- l1mM_rep1_ %>% group_by(transID) %>% summarise(readCount = sum(readCount))

transcript_ids_utr <- l1mM_rep2_[,1]
tmp <- str_split_fixed(transcript_ids_utr, "_", 2)
l1mM_rep2_ <- cbind(tmp,l1mM_rep2_)
colnames(l1mM_rep2_) <- c('transID','utr','Name', 'readCount')
l1mM2 <- l1mM_rep2_ %>% group_by(transID) %>% summarise(readCount = sum(readCount))

# contrl vs 250 ------------------------------------------------

comb <- full_join(con1,con2,by='transID')
comb <- full_join(comb,l2501,by='transID')
comb <- full_join(comb,l2502,by='transID')
comb <- as.data.frame(comb)
rownames(comb) <- comb$transID
comb$transID <- NULL

# construct colData
colnames(comb) <- c('control1','control2','l2501','l2502')
colData <- data.frame(sample=c('control1','control2','l2501','l2502'),treatment = c('unlabel','unlabel','label','label'))
rownames(colData) <- colData$sample
colData$sample <- NULL
countData <- comb[rowSums(comb >0 ) > 1,]

# check if they are the same
all(colnames(countData) %in% rownames(colData))
# check if they are in the same order
all(colnames(comb) == rownames(colData))

# Create DESEq2 dataset.
dds <-  DESeqDataSetFromMatrix(countData=countData, colData=colData, design = ~ treatment)

# filter lowly expressed genes 
keep <-  rowSums(counts(dds)) >= 20
dds <- dds[keep, ]

# set the factor level
dds$treatment <- relevel(dds$treatment,ref = 'unlabel')

# run DESeq2
dds <- DESeq(dds)
res <- results(dds)

# explore result
summary(res)

# change the threshold 
 res0.05 <- results(dds, alpha = 0.05) 
summary(res0.05)

# check comparison
resultsNames(dds)
plotMA(res0.05,main = "0.25mM_4sU vs control_0.09%")

# contrl vs 250 --- bottom ------------------------------------------------


# contrl vs 500 ------------------------------------------------

comb <- full_join(con1,con2,by='transID')
comb <- full_join(comb,l5001,by='transID')
comb <- full_join(comb,l5002,by='transID')
comb <- as.data.frame(comb)
rownames(comb) <- comb$transID
comb$transID <- NULL

# construct colData
colnames(comb) <- c('control1','control2','l5001','l5002')
colData <- data.frame(sample=c('control1','control2','l5001','l5002'),treatment = c('unlabel','unlabel','label','label'))
rownames(colData) <- colData$sample
colData$sample <- NULL
countData <- comb[rowSums(comb >0 ) > 1,]

# check if they are the same
all(colnames(countData) %in% rownames(colData))
# check if they are in the same order
all(colnames(comb) == rownames(colData))

# Create DESEq2 dataset.
dds <-  DESeqDataSetFromMatrix(countData=countData, colData=colData, design = ~ treatment)

# filter lowly expressed genes 
keep <-  rowSums(counts(dds)) >= 20
dds <- dds[keep, ]

# set the factor level
dds$treatment <- relevel(dds$treatment,ref = 'unlabel')

# run DESeq2
dds <- DESeq(dds)
res <- results(dds)

# explore result
summary(res)

# change the threshold 
res0.05 <- results(dds, alpha = 0.05) 
summary(res0.05)

# check comparison
resultsNames(dds)
plotMA(res0.05,main = "0.5mM_4sU vs control_0.22%")

# contrl vs 500 --- bottom ------------------------------------------------


# contrl vs 1mM ------------------------------------------------

comb <- full_join(con1,con2,by='transID')
comb <- full_join(comb,l1mM1,by='transID')
comb <- full_join(comb,l1mM2,by='transID')
comb <- as.data.frame(comb)
rownames(comb) <- comb$transID
comb$transID <- NULL

# construct colData
colnames(comb) <- c('control1','control2','l1mM1','l1mM2')
colData <- data.frame(sample=c('control1','control2','l1mM1','l1mM2'),treatment = c('unlabel','unlabel','label','label'))
rownames(colData) <- colData$sample
colData$sample <- NULL
countData <- comb[rowSums(comb >0 ) > 1,]

# check if they are the same
all(colnames(countData) %in% rownames(colData))
# check if they are in the same order
all(colnames(comb) == rownames(colData))

# Create DESEq2 dataset.
dds <-  DESeqDataSetFromMatrix(countData=countData, colData=colData, design = ~ treatment)

# filter lowly expressed genes 
keep <-  rowSums(counts(dds)) >= 20
dds <- dds[keep, ]

# set the factor level
dds$treatment <- relevel(dds$treatment,ref = 'unlabel')

# run DESeq2
dds <- DESeq(dds)
res <- results(dds)

# explore result
summary(res)

# change the threshold 
res0.05 <- results(dds, alpha = 0.05) 
summary(res0.05)

# check comparison
resultsNames(dds)
plotMA(res0.05,main = "1mM_4sU vs control_0.9%")

```

```{r SF 5a}
# compare average conversion rate, rep1 ----------------

control_rep1 <-read.csv("T_contrl_1_S1_R1_001.fastq_slamdunk_mapped_filtered_tcount.tsv",sep = '\t', comment.char = "#")
l250_rep1 <-read.csv("T_label_250_1_S3_R1_001.fastq_slamdunk_mapped_filtered_tcount.tsv",sep = '\t', comment.char = "#")
l500_rep1 <-read.csv("T_label_500_1_S5_R1_001.fastq_slamdunk_mapped_filtered_tcount.tsv",sep = '\t', comment.char = "#")
l1mM_rep1 <-read.csv("T_label_1K_1_S7_R1_001.fastq_slamdunk_mapped_filtered_tcount.tsv",sep = '\t', comment.char = "#")

control_rep1f <- control_rep1 %>% filter(CoverageOnTs>0&ReadCount >= 50)
l250_rep1f <- l250_rep1 %>% filter(CoverageOnTs>0&ReadCount >= 50)
l500_rep1f <- l500_rep1 %>% filter(CoverageOnTs>0&ReadCount >= 50)
l1mM_rep1f <- l1mM_rep1 %>% filter(CoverageOnTs>0&ReadCount >= 50)

T2Ccontrol <-as_tibble(control_rep1f$ConversionRate) 
T2Ccontrol$type <- rep('no_label',nrow(T2Ccontrol))

T2C250 <-as_tibble(l250_rep1f$ConversionRate) 
T2C250$type <- rep('0.25mM',nrow(T2C250))

T2C500 <-as_tibble(l500_rep1f$ConversionRate) 
T2C500$type <- rep('0.5mM',nrow(T2C500))


T2C1mM <-as_tibble(l1mM_rep1f$ConversionRate) 
T2C1mM$type <- rep('1mM',nrow(T2C1mM))


T2Crate1 <- rbind(T2Ccontrol,T2C250,T2C500,T2C1mM)
T2Crate1$type <- factor(T2Crate1$type,levels = c('no_label','0.25mM','0.5mM','1mM'))
T2Crate1$group <- rep('rep1',nrow(T2Crate1))

# compare average conversion rate, rep2 ----------------

control_rep2 <-read.csv("T_contrl_2_S2_R1_001.fastq_slamdunk_mapped_filtered_tcount.tsv",sep = '\t', comment.char = "#")
l250_rep2 <-read.csv("T_label_250_2_S4_R1_001.fastq_slamdunk_mapped_filtered_tcount.tsv",sep = '\t', comment.char = "#")
l500_rep2 <-read.csv("T_label_500_2_S6_R1_001.fastq_slamdunk_mapped_filtered_tcount.tsv",sep = '\t', comment.char = "#")
l1mM_rep2 <-read.csv("T_label_1K_2_S8_R1_001.fastq_slamdunk_mapped_filtered_tcount.tsv",sep = '\t', comment.char = "#")

control_rep2f <- control_rep2 %>% filter(CoverageOnTs>0&ReadCount >= 50)
l250_rep2f <- l250_rep2 %>% filter(CoverageOnTs>0&ReadCount >= 50)
l500_rep2f <- l500_rep2 %>% filter(CoverageOnTs>0&ReadCount >= 50)
l1mM_rep2f <- l1mM_rep2 %>% filter(CoverageOnTs>0&ReadCount >= 50)

T2Ccontrol_2 <-as_tibble(control_rep2f$ConversionRate) 
T2Ccontrol_2$type <- rep('no_label',nrow(T2Ccontrol_2))

T2C2502 <-as_tibble(l250_rep2f$ConversionRate) 
T2C2502$type <- rep('0.25mM',nrow(T2C2502))


T2C5002 <-as_tibble(l500_rep2f$ConversionRate) 
T2C5002$type <- rep('0.5mM',nrow(T2C5002))


T2C1mM2 <-as_tibble(l1mM_rep2f$ConversionRate) 
T2C1mM2$type <- rep('1mM',nrow(T2C1mM2))


T2Crate2 <- rbind(T2Ccontrol_2,T2C2502,T2C5002,T2C1mM2)
T2Crate2$type <- factor(T2Crate2$type,levels = c('no_label','0.25mM','0.5mM','1mM'))
T2Crate2$group <- rep('rep2',nrow(T2Crate2))

T2Crate <- rbind(T2Crate1,T2Crate2)
T2Crate$value <- as.numeric(T2Crate$value)


p <- ggplot(T2Crate, aes(x=type,y=value*100,color=group)) + 
  stat_boxplot(geom ='errorbar',size=0.25) + 
  geom_boxplot(outlier.shape = NA,lwd=0.25,fatten=1)+
  xlab("4sU concentration") + 
  ylab("Average conversion rate [%]") +
  #scale_fill_manual(values=c("white","white")) + 
  #scale_color_manual(values=c("black", "red")) + 
  theme(axis.ticks.x = element_blank())+ 
  #ylim(0,3)+
  theme_classic()+
  theme(
    axis.text.y = element_text(size=6),
    axis.text.x = element_text(size = 6),
    axis.title = element_text(colour='black', size=7),
    legend.position = c(0.2, 0.9),
    legend.key.size = unit(0.1, "cm"),
    legend.key.width = unit(0.1, "cm"),
    legend.text = element_text(size=5),
    legend.title=element_blank(),
    legend.key=element_blank(),
    axis.line.x = element_line(colour = "black", size=0.25),
    axis.line.y = element_line(colour = "black", size=0.25),
    axis.ticks.x = element_line(colour = "black", size = 0.25),
    axis.ticks.y = element_line(colour = "black", size = 0.25),
    strip.text=element_text(size=7))

ggsave(filename = "labeling_conc_comparison.pdf",plot = p,width=45,height = 45,units = "mm", dpi = 300)

```

